import { BoardTemplate } from './types';

export const BOARD_TEMPLATES: BoardTemplate[] = [
  // 1. Startup GTM & Launch Engine
  {
    id: 'startup-gtm',
    title: 'Startup GTM & Launch Engine',
    category: 'Strategy',
    badge: 'Popular',
    description: 'Structure your value proposition, customer ICP, acquisition channels, and compounding growth loops.',
    suggestedPrompt: 'Read my GTM board, stress-test the acquisition channels against our target persona, and add 3 high-leverage referral mechanics.',
    nodes: [
      {
        title: 'Core Value Proposition',
        body: 'The single clearest reason why customers switch from legacy tools. What painful problem do we solve in under 5 minutes?',
        x: -320,
        y: -120,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Ideal Customer Profile (ICP)',
        body: 'Founder / Head of Product at seed-to-series-A AI startups. They are shipping weekly and need agents to execute real work.',
        x: -320,
        y: 120,
        width: 230,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'Channel: WebMCP Showcase & Devpost',
        body: 'Demonstrate live in-app browser agent pairing. Submit to WebMCP challenge & capture early AI engineer mindshare.',
        x: 60,
        y: -220,
        width: 230,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Channel: Open Source Templates',
        body: 'Give away 20+ strategy & architecture board templates on GitHub. Organic SEO compounding from template searches.',
        x: 60,
        y: -20,
        width: 230,
        color: 'slate',
        author: 'agent',
      },
      {
        title: 'Retention: Shared Multiplayer Boards',
        body: 'When a user shares a live board link with a teammate or agent, virality kicks in. Collaboration creates switching cost.',
        x: 60,
        y: 180,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
      {
        title: 'North Star Metric: Active Co-Sessions',
        body: 'Track weekly active boards where both human edits and agent tool calls occurred within the same 15-minute window.',
        x: 440,
        y: -20,
        width: 230,
        color: 'lavender',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 2, label: 'activates' },
      { sourceIndex: 0, targetIndex: 3, label: 'powers' },
      { sourceIndex: 1, targetIndex: 2, label: 'targets' },
      { sourceIndex: 1, targetIndex: 4, label: 'retains' },
      { sourceIndex: 2, targetIndex: 5, label: 'drives' },
      { sourceIndex: 3, targetIndex: 5, label: 'compounds' },
      { sourceIndex: 4, targetIndex: 5, label: 'measures' },
    ],
  },

  // 2. YC Pitch Deck Blueprint
  {
    id: 'yc-pitch-deck',
    title: 'YC Pitch Deck & Investment Memo',
    category: 'Strategy',
    badge: 'Investor',
    description: 'The standard Y Combinator narrative structure: Problem, Solution, Moat, Traction, TAM, and The Ask.',
    suggestedPrompt: 'Evaluate this pitch narrative from an investor lens, identify any unsupported claims, and suggest 3 defensive moat notes.',
    nodes: [
      {
        title: '1. Massive Problem',
        body: 'AI agents are trapped inside narrow chatbot sidebars with no spatial understanding of long-term human context or workflows.',
        x: -420,
        y: -120,
        width: 230,
        color: 'coral',
        author: 'human',
      },
      {
        title: '2. The Boardify Solution',
        body: 'An infinite spatial whiteboard where agents co-create, arrange, and link thoughts using first-class WebMCP browser tools.',
        x: -140,
        y: -120,
        width: 230,
        color: 'sage',
        author: 'human',
      },
      {
        title: '3. Unfair Advantage / Moat',
        body: 'First native WebMCP implementation standard. Zero network lag, proprietary DAG flow arrangement, and open template ecosystem.',
        x: 140,
        y: -200,
        width: 230,
        color: 'butter',
        author: 'agent',
      },
      {
        title: '4. Market Size & TAM',
        body: '$14B visual collaboration market intersecting the $47B autonomous AI agent tooling wave.',
        x: 140,
        y: -20,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
      {
        title: '5. Early Traction & Velocity',
        body: 'Open source GitHub repo, active WebMCP competition submission, and 100+ co-created whiteboards in initial testing.',
        x: 420,
        y: -120,
        width: 230,
        color: 'slate',
        author: 'human',
      },
      {
        title: '6. The Ask & Roadmap',
        body: 'Raising $1.5M Seed to scale multiplayer CRDT canvas engine, developer SDK, and enterprise compliance connectors.',
        x: 420,
        y: 80,
        width: 230,
        color: 'lavender',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'solved by' },
      { sourceIndex: 1, targetIndex: 2, label: 'defended by' },
      { sourceIndex: 1, targetIndex: 3, label: 'expands into' },
      { sourceIndex: 2, targetIndex: 4, label: 'proven by' },
      { sourceIndex: 3, targetIndex: 4, label: 'measured in' },
      { sourceIndex: 4, targetIndex: 5, label: 'accelerated with' },
    ],
  },

  // 3. Autonomous Multi-Agent Swarm Orchestration
  {
    id: 'multi-agent-swarm',
    title: 'Autonomous Multi-Agent Swarm Flow',
    category: 'Engineering',
    badge: 'Agentic',
    description: 'Architect supervisor coordinators, research subagents, code synthesizers, and verification gates.',
    suggestedPrompt: 'Add a real-time Human-in-the-Loop review checkpoint between Code Synthesizer and Deployment Gateway with connected wires.',
    nodes: [
      {
        title: 'User Intent & Goal Prompt',
        body: 'Human specifies a high-level strategic goal: "Refactor billing system for usage-based tiering."',
        x: -450,
        y: 0,
        width: 220,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Supervisor Agent (Planner)',
        body: 'Decomposes complex goal into DAG tasks. Assigns sub-problems to specialized worker agents with strict timeouts.',
        x: -180,
        y: 0,
        width: 230,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Research & Retrieval Subagent',
        body: 'Scans existing codebase, API docs, and database schema via WebMCP tools. Returns structured knowledge artifacts.',
        x: 100,
        y: -140,
        width: 230,
        color: 'slate',
        author: 'agent',
      },
      {
        title: 'Code Synthesizer Subagent',
        body: 'Generates TypeScript implementation, unit test suites, and schema migration scripts.',
        x: 100,
        y: 140,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
      {
        title: 'QA & Safety Verifier',
        body: 'Executes automated tests, checks linter rules, validates schema security, and computes regression score.',
        x: 380,
        y: 0,
        width: 230,
        color: 'sage',
        author: 'agent',
      },
      {
        title: 'Human Review & Merge Gate',
        body: 'Human clicks "Approve PR" or requests targeted editorial adjustments on the shared canvas.',
        x: 660,
        y: 0,
        width: 220,
        color: 'lavender',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'initiates' },
      { sourceIndex: 1, targetIndex: 2, label: 'delegates research' },
      { sourceIndex: 1, targetIndex: 3, label: 'delegates synthesis' },
      { sourceIndex: 2, targetIndex: 4, label: 'feeds context' },
      { sourceIndex: 3, targetIndex: 4, label: 'verifies code' },
      { sourceIndex: 4, targetIndex: 5, label: 'submits for approval' },
    ],
  },

  // 4. Product Hunt & Hacker News Launch Strategy
  {
    id: 'ph-launch-strategy',
    title: 'Product Hunt & HN Launch Strategy',
    category: 'Strategy',
    badge: 'Growth',
    description: 'Pre-launch teaser phase, launch-day velocity stack, community engagement, and post-launch conversion.',
    suggestedPrompt: 'Add 3 tactical outreach templates for top Product Hunt makers and tech influencers to amplify launch day.',
    nodes: [
      {
        title: 'T-14: Teaser & Waitlist Setup',
        body: 'Build interactive teaser page with live WebMCP demo GIF. Collect 500+ verified email signups on early access list.',
        x: -420,
        y: -100,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'T-7: Top Maker Outreach',
        body: 'Direct outreach to 30 active Product Hunt hunters with exclusive early preview access and 1-click test link.',
        x: -140,
        y: -180,
        width: 230,
        color: 'slate',
        author: 'human',
      },
      {
        title: 'Launch Day: 12:01 AM PST Blitz',
        body: 'Publish clean tagline, first comment story memo, 2-minute Loom demo, and direct ChatGPT WebMCP testing URL.',
        x: -140,
        y: 60,
        width: 230,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Hour 1-8: HN "Show HN" Drop',
        body: 'Post technical breakdown on Hacker News: "Show HN: Boardify – An Open WebMCP Whiteboard for AI Browser Agents".',
        x: 150,
        y: -80,
        width: 230,
        color: 'sage',
        author: 'agent',
      },
      {
        title: 'Hour 9-24: Community AMA',
        body: 'Founder answers technical questions on Discord, Twitter/X, and PH comment thread in real time.',
        x: 440,
        y: -80,
        width: 230,
        color: 'mint',
        author: 'human',
      },
      {
        title: 'Post-Launch: Retention Flywheel',
        body: 'Convert incoming traffic to registered workspace accounts and prompt them to invite co-workers to canvas.',
        x: 440,
        y: 120,
        width: 230,
        color: 'lavender',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'seeds' },
      { sourceIndex: 0, targetIndex: 2, label: 'launches' },
      { sourceIndex: 1, targetIndex: 2, label: 'boosts' },
      { sourceIndex: 2, targetIndex: 3, label: 'cross-posts' },
      { sourceIndex: 3, targetIndex: 4, label: 'drives AMA' },
      { sourceIndex: 4, targetIndex: 5, label: 'converts to' },
    ],
  },

  // 5. Engineering Incident Postmortem
  {
    id: 'incident-postmortem',
    title: 'Engineering Incident Postmortem & RCA',
    category: 'Engineering',
    badge: 'Reliability',
    description: 'Blameless incident analysis: Trigger alert, Impact assessment, Root Cause Analysis, and Preventative Actions.',
    suggestedPrompt: 'Review this incident root cause, apply the 5 Whys framework, and generate 4 preventative engineering tasks.',
    nodes: [
      {
        title: 'Incident: WebMCP Tool RPC Spike',
        body: 'Severity 1: Unthrottled tool call loops caused 429 rate limit errors on LLM inference provider for 14 minutes.',
        x: -420,
        y: 0,
        width: 230,
        color: 'coral',
        author: 'human',
      },
      {
        title: 'Immediate Mitigation',
        body: 'Emergency rollback to client-side debounce cache. Injected rate limiter token bucket into document.modelContext.',
        x: -140,
        y: -120,
        width: 230,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'Root Cause Analysis (5 Whys)',
        body: 'Agent was executing loop without checking return status. Tool definitions lacked exponential backoff metadata.',
        x: -140,
        y: 120,
        width: 230,
        color: 'slate',
        author: 'agent',
      },
      {
        title: 'Action Item: Client Token Bucket',
        body: 'Enforce max 20 tool executions per second on client window. Auto-queue subsequent calls with duration telemetry.',
        x: 160,
        y: -80,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
      {
        title: 'Action Item: Integration E2E Tests',
        body: 'Add Playwright test verifying that infinite loops gracefully degrade without freezing canvas camera or DOM.',
        x: 160,
        y: 120,
        width: 230,
        color: 'butter',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'resolved by' },
      { sourceIndex: 0, targetIndex: 2, label: 'investigated in' },
      { sourceIndex: 2, targetIndex: 3, label: 'fixes root cause' },
      { sourceIndex: 2, targetIndex: 4, label: 'prevents recurrence' },
    ],
  },

  // 6. User Experience & Aha-Moment Map
  {
    id: 'user-journey',
    title: 'User Experience & Aha-Moment Map',
    category: 'Product',
    badge: 'Product',
    description: 'Map user emotion, friction points, agent intervention moments, and the path to initial delight.',
    suggestedPrompt: 'Identify the highest drop-off risk in this journey and add 2 automated agent assists to guide the user to their first win.',
    nodes: [
      {
        title: 'Phase 1: Discovery & Land',
        body: 'User opens Boardify via link or search. Sees pre-seeded interactive sticky notes and immediate live WebMCP status.',
        x: -450,
        y: 0,
        width: 220,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Phase 2: First Note Creation',
        body: 'Double clicks canvas or taps "New note". Types a rough idea or problem statement. Zero onboarding friction.',
        x: -180,
        y: 0,
        width: 220,
        color: 'slate',
        author: 'human',
      },
      {
        title: 'Phase 3: Agent Pulls Up a Chair',
        body: 'Agent in ChatGPT or Agent Studio reads canvas via get_canvas_state. Instantly spawns 4 structured branches with bezier wires.',
        x: 90,
        y: 0,
        width: 220,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Phase 4: The Aha! Moment',
        body: 'User watches the Agent Ghost cursor pan and tidy the board. User realizes: "I never have to stare at a blank whiteboard again."',
        x: 360,
        y: -100,
        width: 230,
        color: 'sage',
        author: 'agent',
      },
      {
        title: 'Phase 5: Export & Ship',
        body: 'User clicks export to Markdown/Mermaid and pastes directly into their engineering sprint ticket or strategy memo.',
        x: 640,
        y: 0,
        width: 220,
        color: 'lavender',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'next' },
      { sourceIndex: 1, targetIndex: 2, label: 'triggers' },
      { sourceIndex: 2, targetIndex: 3, label: 'produces' },
      { sourceIndex: 3, targetIndex: 4, label: 'converts to' },
    ],
  },

  // 7. System Architecture
  {
    id: 'system-architecture',
    title: 'Distributed System & AI Agent Pipeline',
    category: 'Engineering',
    badge: 'Technical',
    description: 'Blueprint microservices, event streams, WebMCP client tool interfaces, and Firestore sync layers.',
    suggestedPrompt: 'Review this architecture for scalability bottlenecks and add a caching layer and rate limiter node with appropriate wires.',
    nodes: [
      {
        title: 'Browser Client (React/Next.js)',
        body: 'Runs Canvas Engine, pan/zoom camera, DOM nodes, SVG wire renderer, and WebMCP listener.',
        x: -400,
        y: -100,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'WebMCP Tool Layer (document.modelContext)',
        body: 'Exposes 15+ deterministic JSON-schema tools. Zero network overhead — runs directly in client window context.',
        x: -100,
        y: -220,
        width: 240,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'AI Browser Agent (ChatGPT / Chrome AI)',
        body: 'Discovers tools automatically on page load. Invokes tool calls with structured JSON parameters.',
        x: -100,
        y: 40,
        width: 240,
        color: 'lavender',
        author: 'agent',
      },
      {
        title: 'Firebase Firestore Realtime DB',
        body: 'Multiplayer synchronizer. Broadcasts note coordinates, text diffs, and live agent cursor positions to all connected peers.',
        x: 230,
        y: -100,
        width: 240,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'Export Engine (PNG / PDF / Markdown / Mermaid)',
        body: 'Serializes graph state into reproducible artifacts for engineering PRs, wikis, and high-res presentation decks.',
        x: 530,
        y: -100,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 2, targetIndex: 1, label: 'calls tools' },
      { sourceIndex: 1, targetIndex: 0, label: 'mutates state' },
      { sourceIndex: 0, targetIndex: 3, label: 'syncs live' },
      { sourceIndex: 3, targetIndex: 4, label: 'exports' },
    ],
  },

  // 8. SWOT Strategic Matrix
  {
    id: 'swot-analysis',
    title: 'Agentic SWOT & Strategic Matrix',
    category: 'Analysis',
    badge: 'Essential',
    description: 'Exhaustive 4-quadrant strategic breakdown comparing internal capabilities with external market shifts.',
    suggestedPrompt: 'Analyze this SWOT board. For each weakness and threat, generate a concrete tactical countermeasure note and link them.',
    nodes: [
      {
        title: 'STRENGTHS: First-mover in WebMCP',
        body: '• Native document.modelContext support\n• Zero round-trip client tool execution\n• High tactile UX polish and delightful feel',
        x: -300,
        y: -200,
        width: 240,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'WEAKNESSES: Emerging Standard Awareness',
        body: '• WebMCP is nascent (requires Chrome flags or ChatGPT browser)\n• Need fallback simulator for standard Safari/Firefox users',
        x: 100,
        y: -200,
        width: 240,
        color: 'coral',
        author: 'human',
      },
      {
        title: 'OPPORTUNITIES: Browser Agent Ecosystem',
        body: '• OpenAI, Google Chrome & Cloudflare pushing WebMCP\n• Millions of ChatGPT users gain in-browser canvas superpowers',
        x: -300,
        y: 120,
        width: 240,
        color: 'mint',
        author: 'agent',
      },
      {
        title: 'THREATS: Legacy Whiteboard Add-ons',
        body: '• Incumbents bolting basic chat sidebars onto existing infinite canvases\n• Must win on agent ergonomics and tool density',
        x: 100,
        y: 120,
        width: 240,
        color: 'butter',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 2, label: 'capitalizes on' },
      { sourceIndex: 1, targetIndex: 3, label: 'vulnerable to' },
    ],
  },
];
