import { BoardTemplate } from './types';

export const BOARD_TEMPLATES: BoardTemplate[] = [
  // =========================================================================
  // 1. AI & FRONTIER AGENT SYSTEMS
  // =========================================================================

  // 1.1 Agentic RAG & Hybrid Vector Search
  {
    id: 'ai-agentic-rag',
    title: 'Agentic RAG & Hybrid Vector Search',
    category: 'AI & Agents',
    badge: 'Frontier AI',
    description: 'Production RAG pipeline with semantic caching, query rewriting, hybrid dense/sparse retrieval, cross-encoder reranker, and reasoning synthesis.',
    suggestedPrompt: 'Analyze this RAG pipeline for cold-start latency bottlenecks and propose a multi-query expansion sub-graph.',
    stackIcons: ['openai', 'claude', 'pinecone', 'redis', 'postgres'],
    tags: ['RAG', 'Vector DB', 'Pinecone', 'Claude', 'OpenAI', 'Redis', 'AI'],
    nodes: [
      {
        title: 'Agentic RAG with Hybrid Retrieval',
        body: 'End-to-end production architecture for low-latency context grounding',
        x: 0,
        y: -300,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'Client Query',
        body: 'Conversational chat or enterprise document question',
        x: -420,
        y: -140,
        width: 170,
        color: 'butter',
        author: 'human',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
      {
        title: 'Redis Semantic Cache',
        body: 'Checks vector distance for previous identical answers (p99 < 8ms)',
        x: -180,
        y: -220,
        width: 190,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'redis',
      },
      {
        title: 'Query Expansion Agent',
        body: 'HyDE hallucination prompt & keyword decomposition',
        x: -180,
        y: -60,
        width: 190,
        color: 'lavender',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'langchain',
      },
      {
        title: 'Embedding Model',
        body: 'text-embedding-3-large (3072 dimensions)',
        x: 80,
        y: -160,
        width: 170,
        color: 'mint',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'openai',
      },
      {
        title: 'Pinecone Vector Store',
        body: 'Dense HNSW index partitioned by customer org_id',
        x: 320,
        y: -240,
        width: 180,
        color: 'sage',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'pinecone',
      },
      {
        title: 'PostgreSQL Fulltext',
        body: 'Sparse BM25 search for exact SKU, numbers, and identifiers',
        x: 320,
        y: -80,
        width: 180,
        color: 'slate',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'postgres',
      },
      {
        title: 'Cross-Encoder Reranker',
        body: 'Cohere Rerank v3 blends top-50 results to top-5 most relevant chunks',
        x: 580,
        y: -160,
        width: 180,
        color: 'coral',
        author: 'agent',
        nodeType: 'shape',
        shapeType: 'hexagon',
      },
      {
        title: 'Claude 3.7 Sonnet',
        body: 'Extended thinking synthesis with inline citation verification',
        x: 820,
        y: -160,
        width: 180,
        color: 'butter',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'claude',
      },
      {
        title: 'Stream Response',
        body: 'Server-Sent Events (SSE) stream back to web UI with source chips',
        x: 1060,
        y: -160,
        width: 160,
        color: 'mint',
        author: 'human',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: '1. Check cache' },
      { sourceIndex: 1, targetIndex: 3, label: '2. Cache miss' },
      { sourceIndex: 3, targetIndex: 4, label: 'Generate vectors' },
      { sourceIndex: 4, targetIndex: 5, label: 'Dense KNN' },
      { sourceIndex: 3, targetIndex: 6, label: 'Sparse BM25' },
      { sourceIndex: 5, targetIndex: 7, label: 'Top 50 matches' },
      { sourceIndex: 6, targetIndex: 7, label: 'Top 50 matches' },
      { sourceIndex: 7, targetIndex: 8, label: 'Top 5 context' },
      { sourceIndex: 8, targetIndex: 9, label: 'Token stream' },
    ],
  },

  // 1.2 Multi-Agent Autonomous Swarm (WebMCP)
  {
    id: 'ai-webmcp-swarm',
    title: 'Multi-Agent Autonomous Swarm (WebMCP)',
    category: 'AI & Agents',
    badge: 'WebMCP Standard',
    description: 'Collaborative agent collective where specialized agents (Code, Research, Verification) communicate via shared memory and execute live browser tools.',
    suggestedPrompt: 'Review the tool invocation loop and add a specialized security compliance agent to inspect generated terminal scripts.',
    stackIcons: ['webmcp', 'gemini', 'deepseek', 'docker', 'vscode'],
    tags: ['WebMCP', 'Multi-Agent', 'Autonomous', 'Docker', 'Gemini', 'DeepSeek'],
    nodes: [
      {
        title: 'Autonomous Swarm with WebMCP Tools',
        body: 'Hierarchical multi-agent network orchestrated over live browser tool protocol',
        x: 0,
        y: -280,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'User Mission Goal',
        body: '"Refactor authentication layer to support Passkeys and OAuth2"',
        x: -420,
        y: -60,
        width: 180,
        color: 'butter',
        author: 'human',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
      {
        title: 'Supervisor Agent',
        body: 'Gemini 2.5 Flash / Claude planner decomposing goals into DAG tasks',
        x: -180,
        y: -60,
        width: 180,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'gemini',
      },
      {
        title: 'Shared Memory Blackboard',
        body: 'Redis Key-Value store holding current plan state & tool execution logs',
        x: 80,
        y: -220,
        width: 180,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'redis',
      },
      {
        title: 'Research Agent',
        body: 'Perplexity / Tavily real-time web crawler inspecting modern specs',
        x: 80,
        y: -60,
        width: 170,
        color: 'mint',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'perplexity',
      },
      {
        title: 'Code Synthesis Agent',
        body: 'DeepSeek R1 reasoning model writing TypeScript implementation',
        x: 80,
        y: 100,
        width: 170,
        color: 'lavender',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'deepseek',
      },
      {
        title: 'WebMCP Tool Host',
        body: 'Standard browser MCP runtime registering live canvas and DOM controls',
        x: 340,
        y: -60,
        width: 180,
        color: 'butter',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'webmcp',
      },
      {
        title: 'Docker Sandbox',
        body: 'Isolated container executing test suites and verifying TypeScript builds',
        x: 580,
        y: -60,
        width: 170,
        color: 'slate',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'docker',
      },
      {
        title: 'Human Review Gate',
        body: 'Inspect proposed architecture on canvas before committing to git',
        x: 820,
        y: -60,
        width: 170,
        color: 'sage',
        author: 'human',
        nodeType: 'shape',
        shapeType: 'diamond',
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: 'Assigns goal' },
      { sourceIndex: 2, targetIndex: 3, label: 'Syncs state' },
      { sourceIndex: 2, targetIndex: 4, label: 'Dispatches research' },
      { sourceIndex: 2, targetIndex: 5, label: 'Dispatches coding' },
      { sourceIndex: 4, targetIndex: 6, label: 'Web search tool' },
      { sourceIndex: 5, targetIndex: 6, label: 'Call WebMCP' },
      { sourceIndex: 6, targetIndex: 7, label: 'Run container test' },
      { sourceIndex: 7, targetIndex: 8, label: 'PR review' },
    ],
  },

  // 1.3 Local AI & Edge Inference Architecture
  {
    id: 'ai-local-inference',
    title: 'Local AI & Edge Inference Pipeline',
    category: 'AI & Agents',
    badge: '100% Private',
    description: 'Air-gapped on-device AI architecture running Ollama, ChromaDB, and local WebMCP tools with zero telemetry or cloud egress.',
    suggestedPrompt: 'Identify any performance bottlenecks between on-device quantized model inference and SQLite vector search.',
    stackIcons: ['ollama', 'chroma', 'webmcp', 'linux', 'python'],
    tags: ['Local AI', 'Ollama', 'Private', 'ChromaDB', 'Edge', 'Linux'],
    nodes: [
      {
        title: 'Air-Gapped Private Local AI',
        body: 'Zero-cloud egress local developer workstation architecture',
        x: 0,
        y: -240,
        width: 360,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'Workstation App',
        body: 'Local Electron or Web App running on localhost:3000',
        x: -360,
        y: -40,
        width: 170,
        color: 'butter',
        author: 'human',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
      {
        title: 'Ollama Engine',
        body: 'Llama 3.3 70B & DeepSeek R1 running on local Apple Silicon / CUDA',
        x: -120,
        y: -40,
        width: 180,
        color: 'slate',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'ollama',
      },
      {
        title: 'ChromaDB Local Store',
        body: 'Local DuckDB/Parquet vector embeddings persisted on SSD',
        x: 140,
        y: -120,
        width: 170,
        color: 'mint',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'chroma',
      },
      {
        title: 'Local WebMCP Bridge',
        body: 'Localhost stdio/SSE socket connecting AI to local project filesystem',
        x: 140,
        y: 40,
        width: 170,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'webmcp',
      },
      {
        title: 'Host Linux Kernel',
        body: 'Local sandboxed file read/write and git branch commits',
        x: 380,
        y: -40,
        width: 170,
        color: 'slate',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'linux',
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: 'HTTP /api/chat' },
      { sourceIndex: 2, targetIndex: 3, label: 'Local embeddings' },
      { sourceIndex: 2, targetIndex: 4, label: 'Tool call dispatch' },
      { sourceIndex: 4, targetIndex: 5, label: 'Local file ops' },
    ],
  },

  // =========================================================================
  // 2. CLOUD & MICROSERVICES
  // =========================================================================

  // 2.1 High-Scale Event-Driven Cloud Microservices
  {
    id: 'cloud-event-driven-microservices',
    title: 'High-Scale Event-Driven Cloud Microservices',
    category: 'Cloud & Infra',
    badge: 'Enterprise',
    description: 'Distributed microservices architecture with Cloudflare edge, AWS API Gateway, Apache Kafka event backbone, and read/write database segregation.',
    suggestedPrompt: 'Simulate a sudden 10x traffic spike on the Order Service and verify Kafka consumer group backpressure dynamics.',
    stackIcons: ['aws', 'kubernetes', 'docker', 'kafka', 'postgres', 'redis'],
    tags: ['Microservices', 'Kafka', 'Kubernetes', 'AWS', 'Postgres', 'Redis'],
    nodes: [
      {
        title: 'Event-Driven Cloud Microservices Mesh',
        body: 'Resilient multi-service cluster scaling to millions of daily transactions',
        x: 0,
        y: -300,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'Cloudflare Edge CDN',
        body: 'DDoS mitigation, TLS termination, and edge caching (p99 < 15ms)',
        x: -420,
        y: -120,
        width: 180,
        color: 'coral',
        author: 'human',
        nodeType: 'logo',
        logoType: 'cloudflare',
      },
      {
        title: 'AWS API Gateway',
        body: 'Token validation, rate throttling, and path-based service routing',
        x: -180,
        y: -120,
        width: 180,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'awsapigateway',
      },
      {
        title: 'Kafka Event Bus',
        body: 'Distributed multi-partition log topic ("order.created", "inventory.reserved")',
        x: 80,
        y: -120,
        width: 180,
        color: 'butter',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'kafka',
      },
      {
        title: 'Order Service (K8s)',
        body: 'Scalable Docker pods handling order validation & state machines',
        x: 320,
        y: -220,
        width: 180,
        color: 'mint',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'docker',
      },
      {
        title: 'Billing Microservice',
        body: 'Stripe integration with idempotent webhook processing',
        x: 320,
        y: -40,
        width: 180,
        color: 'lavender',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'stripe',
      },
      {
        title: 'PostgreSQL Primary',
        body: 'ACID compliant transactional writes with WAL replication',
        x: 580,
        y: -220,
        width: 180,
        color: 'slate',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'postgres',
      },
      {
        title: 'Redis Cluster Cache',
        body: 'Sub-millisecond inventory counters and active user sessions',
        x: 580,
        y: -40,
        width: 180,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'redis',
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: 'HTTPS Request' },
      { sourceIndex: 2, targetIndex: 3, label: 'Ingest Event' },
      { sourceIndex: 3, targetIndex: 4, label: 'Consume "orders"' },
      { sourceIndex: 3, targetIndex: 5, label: 'Consume "payments"' },
      { sourceIndex: 4, targetIndex: 6, label: 'Transactional Write' },
      { sourceIndex: 4, targetIndex: 7, label: 'Cache Lookup' },
      { sourceIndex: 5, targetIndex: 6, label: 'Update Status' },
    ],
  },

  // 2.2 Modern Next.js 15 Fullstack SaaS Production Engine
  {
    id: 'cloud-nextjs-saas-engine',
    title: 'Modern Next.js 15 Fullstack SaaS Blueprint',
    category: 'Cloud & Infra',
    badge: 'Modern SaaS',
    description: 'The golden standard tech stack for 2026 SaaS: Next.js App Router, Clerk Auth, Stripe Webhooks, Supabase PostgreSQL, Upstash Redis, and Resend.',
    suggestedPrompt: 'Examine our billing webhook flow and add an automated email sequence trigger for card expiration warnings.',
    stackIcons: ['nextjs', 'clerk', 'stripe', 'supabase', 'redis', 'netlify'],
    tags: ['Next.js', 'SaaS', 'Stripe', 'Supabase', 'Clerk', 'TypeScript'],
    nodes: [
      {
        title: 'Next.js 15 Fullstack SaaS Engine',
        body: 'Server Components, Server Actions, edge auth, and billing infrastructure',
        x: 0,
        y: -280,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'Next.js 15 App Router',
        body: 'React 19 Server Components, streaming SSR, and Server Actions',
        x: -340,
        y: -80,
        width: 180,
        color: 'slate',
        author: 'human',
        nodeType: 'logo',
        logoType: 'nextjs',
      },
      {
        title: 'Clerk Authentication',
        body: 'Multi-tenant organization switcher, MFA, and JWT session verify',
        x: -80,
        y: -180,
        width: 170,
        color: 'lavender',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'clerk',
      },
      {
        title: 'Stripe Billing Webhooks',
        body: 'Subscriptions, usage billing, metered tiers, and invoice lifecycles',
        x: -80,
        y: 20,
        width: 170,
        color: 'butter',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'stripe',
      },
      {
        title: 'Supabase PostgreSQL',
        body: 'Row Level Security (RLS) policies protecting tenant customer records',
        x: 180,
        y: -180,
        width: 180,
        color: 'mint',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'supabase',
      },
      {
        title: 'Upstash Redis',
        body: 'Serverless rate limiting (@upstash/ratelimit) preventing abuse',
        x: 180,
        y: 20,
        width: 180,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'redis',
      },
      {
        title: 'Production Readiness Checklist',
        body: 'Verify all operational gates before public customer onboarding',
        x: 460,
        y: -80,
        width: 240,
        color: 'mint',
        author: 'human',
        nodeType: 'task',
        tasks: [
          { id: 't1', text: 'Configure custom domain & SSL on Netlify', done: true },
          { id: 't2', text: 'Activate Stripe live mode webhook signing secret', done: true },
          { id: 't3', text: 'Enforce Postgres Row Level Security (RLS)', done: false },
          { id: 't4', text: 'Set Upstash IP rate limiting for API routes', done: false },
        ],
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: 'Auth Token' },
      { sourceIndex: 1, targetIndex: 3, label: 'Checkout Session' },
      { sourceIndex: 1, targetIndex: 4, label: 'Prisma/Drizzle Query' },
      { sourceIndex: 1, targetIndex: 5, label: 'Check Rate Limit' },
      { sourceIndex: 3, targetIndex: 4, label: 'Sync Webhook State' },
    ],
  },

  // 2.3 Real-Time Collaborative Whiteboard Infrastructure
  {
    id: 'cloud-realtime-whiteboard',
    title: 'Real-Time Collaborative Whiteboard Infrastructure',
    category: 'Cloud & Infra',
    badge: 'Real-time',
    description: 'Figma/Miro-grade multi-cursor spatial whiteboard architecture with WebSocket gateway, Redis Pub/Sub, CRDT conflict resolution, and S3 snapshotting.',
    suggestedPrompt: 'Calculate the maximum concurrent active users per room before Redis Pub/Sub saturation, and propose an OT/CRDT compaction schedule.',
    stackIcons: ['react', 'redis', 'node', 'awss3', 'postgres'],
    tags: ['Realtime', 'WebSockets', 'CRDT', 'Redis', 'React', 'AWS S3'],
    nodes: [
      {
        title: 'Real-Time Multiplayer Canvas Architecture',
        body: 'Low-latency distributed state sync with CRDT conflict-free replication',
        x: 0,
        y: -260,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'Collaborating Clients',
        body: 'React 19 Canvas with local optimistic rendering and cursor interpolation',
        x: -380,
        y: -40,
        width: 180,
        color: 'mint',
        author: 'human',
        nodeType: 'logo',
        logoType: 'react',
      },
      {
        title: 'WebSocket Edge Nodes',
        body: 'Node.js/Bun WebSocket cluster handling sticky room connections',
        x: -140,
        y: -40,
        width: 170,
        color: 'butter',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'node',
      },
      {
        title: 'Redis Pub/Sub Matrix',
        body: 'Cross-node message fanout with ephemeral room presence keys',
        x: 100,
        y: -140,
        width: 170,
        color: 'coral',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'redis',
      },
      {
        title: 'CRDT Merger Engine',
        body: 'Yjs / Automerge conflict-free causal DAG ordering',
        x: 100,
        y: 60,
        width: 170,
        color: 'lavender',
        author: 'agent',
        nodeType: 'shape',
        shapeType: 'hexagon',
      },
      {
        title: 'Amazon S3 Snapshots',
        body: 'Periodic compressed room scene dumps every 60 seconds',
        x: 340,
        y: -40,
        width: 170,
        color: 'sage',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'awss3',
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: 'wss:// delta stream' },
      { sourceIndex: 2, targetIndex: 3, label: 'Publish delta' },
      { sourceIndex: 3, targetIndex: 4, label: 'Resolve conflict' },
      { sourceIndex: 4, targetIndex: 2, label: 'Broadcast ack' },
      { sourceIndex: 4, targetIndex: 5, label: 'Snapshot commit' },
    ],
  },

  // =========================================================================
  // 3. DATABASES & ER DIAGRAMS (ERD TABLES)
  // =========================================================================

  // 3.1 B2B SaaS Multi-Tenant Database
  {
    id: 'erd-saas-multitenant',
    title: 'B2B SaaS Multi-Tenant Database Schema',
    category: 'Databases & ERD',
    badge: 'SQL ERD',
    description: 'Production PostgreSQL relational model for multi-tenant B2B apps featuring organizations, users, roles, subscriptions, projects, and security audit logs.',
    suggestedPrompt: 'Review the foreign key cascade behaviors and verify GDPR user data deletion isolation across all child tables.',
    stackIcons: ['postgres', 'prisma'],
    tags: ['Postgres', 'SQL', 'ERD', 'Database', 'Multi-tenant', 'SaaS'],
    nodes: [
      {
        title: 'B2B SaaS Relational Entity Schema',
        body: 'Multi-tenant database schema with strict foreign key constraints & indexing',
        x: 0,
        y: -300,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'organizations',
        body: 'Tenant organization root',
        x: -380,
        y: -140,
        width: 250,
        color: 'mint',
        author: 'human',
        nodeType: 'entity',
        fields: [
          { id: 'o1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'o2', name: 'name', type: 'VARCHAR(100)' },
          { id: 'o3', name: 'slug', type: 'VARCHAR(64)' },
          { id: 'o4', name: 'plan_tier', type: 'VARCHAR(32)' },
          { id: 'o5', name: 'created_at', type: 'TIMESTAMP' },
        ],
      },
      {
        title: 'users',
        body: 'Global user identity accounts',
        x: 360,
        y: -140,
        width: 250,
        color: 'slate',
        author: 'human',
        nodeType: 'entity',
        fields: [
          { id: 'u1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'u2', name: 'email', type: 'VARCHAR(255)' },
          { id: 'u3', name: 'full_name', type: 'VARCHAR(100)' },
          { id: 'u4', name: 'mfa_enabled', type: 'BOOLEAN' },
          { id: 'u5', name: 'created_at', type: 'TIMESTAMP' },
        ],
      },
      {
        title: 'memberships',
        body: 'Tenant user association & RBAC',
        x: 0,
        y: -140,
        width: 250,
        color: 'butter',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'm1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'm2', name: 'org_id', type: 'UUID', isForeignKey: true, foreignTable: 'organizations' },
          { id: 'm3', name: 'user_id', type: 'UUID', isForeignKey: true, foreignTable: 'users' },
          { id: 'm4', name: 'role', type: 'VARCHAR(32)' },
        ],
      },
      {
        title: 'subscriptions',
        body: 'Stripe billing status & period',
        x: -380,
        y: 120,
        width: 250,
        color: 'coral',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 's1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 's2', name: 'org_id', type: 'UUID', isForeignKey: true, foreignTable: 'organizations' },
          { id: 's3', name: 'stripe_sub_id', type: 'VARCHAR(128)' },
          { id: 's4', name: 'status', type: 'VARCHAR(32)' },
          { id: 's5', name: 'current_period_end', type: 'TIMESTAMP' },
        ],
      },
      {
        title: 'projects',
        body: 'Customer workspaces & boards',
        x: 0,
        y: 120,
        width: 250,
        color: 'lavender',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'p1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'p2', name: 'org_id', type: 'UUID', isForeignKey: true, foreignTable: 'organizations' },
          { id: 'p3', name: 'title', type: 'VARCHAR(120)' },
          { id: 'p4', name: 'settings', type: 'JSONB' },
        ],
      },
      {
        title: 'audit_logs',
        body: 'Compliance access tracking',
        x: 360,
        y: 120,
        width: 250,
        color: 'slate',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'a1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'a2', name: 'org_id', type: 'UUID', isForeignKey: true, foreignTable: 'organizations' },
          { id: 'a3', name: 'user_id', type: 'UUID', isForeignKey: true, foreignTable: 'users' },
          { id: 'a4', name: 'action', type: 'VARCHAR(128)' },
          { id: 'a5', name: 'ip_address', type: 'VARCHAR(45)' },
        ],
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 3, label: '1 : N' },
      { sourceIndex: 2, targetIndex: 3, label: '1 : N' },
      { sourceIndex: 1, targetIndex: 4, label: '1 : 1' },
      { sourceIndex: 1, targetIndex: 5, label: '1 : N' },
      { sourceIndex: 1, targetIndex: 6, label: '1 : N' },
    ],
  },

  // 3.2 E-Commerce & Marketplace Entity Engine
  {
    id: 'erd-ecommerce-engine',
    title: 'E-Commerce Marketplace Relational Schema',
    category: 'Databases & ERD',
    badge: 'SQL ERD',
    description: 'High-throughput marketplace database design with merchants, catalog products, inventory locking, checkout orders, and payment records.',
    suggestedPrompt: 'Analyze this schema for concurrency lock contention during flash sale events on the inventory table.',
    stackIcons: ['postgres', 'mysql'],
    tags: ['E-Commerce', 'Postgres', 'SQL', 'Inventory', 'Orders', 'Payments'],
    nodes: [
      {
        title: 'Marketplace Core Relational Architecture',
        body: 'Normalized 3NF relational data model supporting high-volume checkouts',
        x: 0,
        y: -320,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'merchants',
        body: 'Seller store accounts',
        x: -400,
        y: -140,
        width: 250,
        color: 'mint',
        author: 'human',
        nodeType: 'entity',
        fields: [
          { id: 'm1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'm2', name: 'store_name', type: 'VARCHAR(120)' },
          { id: 'm3', name: 'payout_account', type: 'VARCHAR(128)' },
          { id: 'm4', name: 'status', type: 'VARCHAR(32)' },
        ],
      },
      {
        title: 'products',
        body: 'Catalog item listings',
        x: -120,
        y: -140,
        width: 250,
        color: 'butter',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'p1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'p2', name: 'merchant_id', type: 'UUID', isForeignKey: true, foreignTable: 'merchants' },
          { id: 'p3', name: 'title', type: 'VARCHAR(255)' },
          { id: 'p4', name: 'price', type: 'DECIMAL(10,2)' },
          { id: 'p5', name: 'sku', type: 'VARCHAR(64)' },
        ],
      },
      {
        title: 'inventory',
        body: 'Real-time warehouse stock',
        x: -120,
        y: 120,
        width: 250,
        color: 'coral',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'i1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'i2', name: 'product_id', type: 'UUID', isForeignKey: true, foreignTable: 'products' },
          { id: 'i3', name: 'stock_quantity', type: 'INT' },
          { id: 'i4', name: 'reserved_qty', type: 'INT' },
        ],
      },
      {
        title: 'customers',
        body: 'Shopper user profiles',
        x: 160,
        y: -140,
        width: 250,
        color: 'slate',
        author: 'human',
        nodeType: 'entity',
        fields: [
          { id: 'c1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'c2', name: 'email', type: 'VARCHAR(255)' },
          { id: 'c3', name: 'name', type: 'VARCHAR(100)' },
          { id: 'c4', name: 'shipping_address', type: 'JSONB' },
        ],
      },
      {
        title: 'orders',
        body: 'Completed buyer checkouts',
        x: 440,
        y: -140,
        width: 250,
        color: 'lavender',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'o1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'o2', name: 'customer_id', type: 'UUID', isForeignKey: true, foreignTable: 'customers' },
          { id: 'o3', name: 'total_amount', type: 'DECIMAL(10,2)' },
          { id: 'o4', name: 'status', type: 'VARCHAR(32)' },
          { id: 'o5', name: 'ordered_at', type: 'TIMESTAMP' },
        ],
      },
      {
        title: 'order_items',
        body: 'Individual line items',
        x: 160,
        y: 120,
        width: 250,
        color: 'butter',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'oi1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'oi2', name: 'order_id', type: 'UUID', isForeignKey: true, foreignTable: 'orders' },
          { id: 'oi3', name: 'product_id', type: 'UUID', isForeignKey: true, foreignTable: 'products' },
          { id: 'oi4', name: 'quantity', type: 'INT' },
          { id: 'oi5', name: 'unit_price', type: 'DECIMAL(10,2)' },
        ],
      },
      {
        title: 'payments',
        body: 'Gateway capture ledger',
        x: 440,
        y: 120,
        width: 250,
        color: 'mint',
        author: 'agent',
        nodeType: 'entity',
        fields: [
          { id: 'pm1', name: 'id', type: 'UUID', isPrimaryKey: true },
          { id: 'pm2', name: 'order_id', type: 'UUID', isForeignKey: true, foreignTable: 'orders' },
          { id: 'pm3', name: 'gateway_ref', type: 'VARCHAR(128)' },
          { id: 'pm4', name: 'amount', type: 'DECIMAL(10,2)' },
          { id: 'pm5', name: 'status', type: 'VARCHAR(32)' },
        ],
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: '1 : N' },
      { sourceIndex: 2, targetIndex: 3, label: '1 : 1' },
      { sourceIndex: 4, targetIndex: 5, label: '1 : N' },
      { sourceIndex: 5, targetIndex: 6, label: '1 : N' },
      { sourceIndex: 2, targetIndex: 6, label: '1 : N' },
      { sourceIndex: 5, targetIndex: 7, label: '1 : 1' },
    ],
  },

  // =========================================================================
  // 4. PRODUCT & SYSTEM DESIGN
  // =========================================================================

  // 4.1 Stripe Subscription Lifecycle & Dunning
  {
    id: 'product-stripe-lifecycle',
    title: 'Stripe Subscription Lifecycle & Dunning State Machine',
    category: 'Product & SaaS',
    badge: 'Fintech',
    description: 'Complete state machine mapping user trial, activation, failed invoice dunning retries, grace period, and churn recovery offers.',
    suggestedPrompt: 'Propose automated win-back discount promotions for customers who enter the Canceled state.',
    stackIcons: ['stripe', 'resend', 'react'],
    tags: ['Stripe', 'Billing', 'SaaS', 'Dunning', 'State Machine', 'Fintech'],
    nodes: [
      {
        title: 'Stripe Billing State Machine',
        body: 'Deterministic event transitions handling payment success, decline, and recovery',
        x: 0,
        y: -260,
        width: 380,
        color: 'slate',
        author: 'human',
        nodeType: 'heading',
      },
      {
        title: 'Trial Started (14 Days)',
        body: 'Full feature access without upfront credit card commitment',
        x: -400,
        y: -60,
        width: 170,
        color: 'mint',
        author: 'human',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
      {
        title: 'Active Subscription',
        body: 'Customer successfully charged on recurring monthly/annual billing cycle',
        x: -150,
        y: -60,
        width: 180,
        color: 'mint',
        author: 'agent',
        nodeType: 'logo',
        logoType: 'stripe',
      },
      {
        title: 'Payment Failed',
        body: 'Card declined or insufficient funds webhook (invoice.payment_failed)',
        x: 120,
        y: -60,
        width: 170,
        color: 'coral',
        author: 'agent',
        nodeType: 'shape',
        shapeType: 'diamond',
      },
      {
        title: 'Smart Dunning Sequence',
        body: 'Automated 3-attempt Smart Retries with in-app banner warnings',
        x: 360,
        y: -140,
        width: 180,
        color: 'coral',
        author: 'agent',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
      {
        title: 'Account Reactivated',
        body: 'Payment recovered on retry #2; subscription returns to Good Standing',
        x: 620,
        y: -140,
        width: 170,
        color: 'mint',
        author: 'agent',
        nodeType: 'shape',
        shapeType: 'circle',
      },
      {
        title: 'Grace Period Expired',
        body: '7-day dunning window closed without payment method update',
        x: 360,
        y: 40,
        width: 180,
        color: 'butter',
        author: 'agent',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
      {
        title: 'Subscription Canceled',
        body: 'Access restricted to read-only; trigger churn exit survey & email',
        x: 620,
        y: 40,
        width: 170,
        color: 'slate',
        author: 'human',
        nodeType: 'shape',
        shapeType: 'rectangle',
      },
    ],
    edges: [
      { sourceIndex: 1, targetIndex: 2, label: 'Trial Converted' },
      { sourceIndex: 2, targetIndex: 3, label: 'Monthly Charge Fails' },
      { sourceIndex: 3, targetIndex: 4, label: 'Start Dunning' },
      { sourceIndex: 4, targetIndex: 5, label: 'Retry Success' },
      { sourceIndex: 4, targetIndex: 6, label: '3 Retries Exhausted' },
      { sourceIndex: 6, targetIndex: 7, label: 'Auto Cancel' },
      { sourceIndex: 5, targetIndex: 2, label: 'Restore Access' },
    ],
  },

  // 4.2 Startup GTM & Launch Engine
  {
    id: 'startup-gtm',
    title: 'Startup GTM & Launch Engine',
    category: 'Strategy',
    badge: 'Popular',
    description: 'Structure your value proposition, customer ICP, acquisition channels, and compounding growth loops.',
    suggestedPrompt: 'Read my GTM board, stress-test the acquisition channels against our target persona, and add 3 high-leverage referral mechanics.',
    tags: ['GTM', 'Strategy', 'Growth', 'Startup', 'Launch'],
    nodes: [
      {
        title: 'Core Value Proposition',
        body: 'The single clearest reason why customers switch from legacy tools. What painful problem do we solve in under 5 minutes?',
        x: -320,
        y: -120,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Ideal Customer Profile (ICP)',
        body: 'Founder / Head of Product at seed-to-series-A AI startups. They are shipping weekly and need agents to execute real work.',
        x: -320,
        y: 120,
        width: 230,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'Channel: WebMCP Showcase & Devpost',
        body: 'Demonstrate live in-app browser agent pairing. Submit to WebMCP challenge & capture early AI engineer mindshare.',
        x: 60,
        y: -220,
        width: 230,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Channel: Open Source Templates',
        body: 'Give away 20+ strategy & architecture board templates on GitHub. Organic SEO compounding from template searches.',
        x: 60,
        y: -20,
        width: 230,
        color: 'slate',
        author: 'agent',
      },
      {
        title: 'Retention: Shared Multiplayer Boards',
        body: 'When a user shares a live board link with a teammate or agent, virality kicks in. Collaboration creates switching cost.',
        x: 60,
        y: 180,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
      {
        title: 'North Star Metric: Active Co-Sessions',
        body: 'Track weekly active boards where both human edits and agent tool calls occurred within the same 15-minute window.',
        x: 440,
        y: -20,
        width: 230,
        color: 'lavender',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 2, label: 'activates' },
      { sourceIndex: 0, targetIndex: 3, label: 'powers' },
      { sourceIndex: 1, targetIndex: 2, label: 'targets' },
      { sourceIndex: 1, targetIndex: 4, label: 'retains' },
      { sourceIndex: 2, targetIndex: 5, label: 'drives' },
      { sourceIndex: 3, targetIndex: 5, label: 'compounds' },
      { sourceIndex: 4, targetIndex: 5, label: 'measures' },
    ],
  },

  // 4.3 YC Pitch Deck & Investment Memo
  {
    id: 'yc-pitch-deck',
    title: 'YC Pitch Deck & Investment Memo',
    category: 'Strategy',
    badge: 'Investor',
    description: 'The standard Y Combinator narrative structure: Problem, Solution, Moat, Traction, TAM, and The Ask.',
    suggestedPrompt: 'Evaluate this pitch narrative from an investor lens, identify any unsupported claims, and suggest 3 defensive moat notes.',
    tags: ['Pitch', 'YC', 'Investor', 'Fundraising', 'Deck'],
    nodes: [
      {
        title: '1. Massive Problem',
        body: 'AI agents are trapped inside narrow chatbot sidebars with no spatial understanding of long-term human context or workflows.',
        x: -420,
        y: -120,
        width: 230,
        color: 'coral',
        author: 'human',
      },
      {
        title: '2. The Boardify Solution',
        body: 'An infinite spatial whiteboard where agents co-create, arrange, and link thoughts using first-class WebMCP browser tools.',
        x: -140,
        y: -120,
        width: 230,
        color: 'sage',
        author: 'human',
      },
      {
        title: '3. Unfair Advantage / Moat',
        body: 'First native WebMCP implementation standard. Zero network lag, proprietary DAG flow arrangement, and open template ecosystem.',
        x: 140,
        y: -200,
        width: 230,
        color: 'butter',
        author: 'agent',
      },
      {
        title: '4. Market Size & TAM',
        body: '$14B visual collaboration market intersecting the $47B autonomous AI agent tooling wave.',
        x: 140,
        y: -20,
        width: 230,
        color: 'lavender',
        author: 'agent',
      },
      {
        title: '5. The Ask & Milestones',
        body: 'Raising $2M seed round to scale the WebMCP agent registry and build multiplayer collaboration infrastructure.',
        x: 420,
        y: -120,
        width: 230,
        color: 'mint',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'solved by' },
      { sourceIndex: 1, targetIndex: 2, label: 'defended by' },
      { sourceIndex: 1, targetIndex: 3, label: 'expands into' },
      { sourceIndex: 2, targetIndex: 4, label: 'capitalized by' },
      { sourceIndex: 3, targetIndex: 4, label: 'funds roadmap' },
    ],
  },
];
