import { BoardTemplate } from './types';

export const BOARD_TEMPLATES: BoardTemplate[] = [
  {
    id: 'startup-gtm',
    title: 'Startup GTM & Launch Engine',
    category: 'Strategy',
    badge: 'Popular',
    description: 'Structure your value proposition, customer ICP, acquisition channels, and compounding growth loops.',
    suggestedPrompt: 'Read my GTM board, stress-test the acquisition channels against our target persona, and add 3 high-leverage referral mechanics.',
    nodes: [
      {
        title: 'Core Value Proposition',
        body: 'The single clearest reason why customers switch from legacy tools. What painful problem do we solve in under 5 minutes?',
        x: -320,
        y: -120,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Ideal Customer Profile (ICP)',
        body: 'Founder / Head of Product at seed-to-series-A AI startups. They are shipping weekly and need agents to execute real work.',
        x: -320,
        y: 120,
        width: 230,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'Channel: WebMCP Showcase & Devpost',
        body: 'Demonstrate live in-app browser agent pairing. Submit to WebMCP challenge & capture early AI engineer mindshare.',
        x: 60,
        y: -220,
        width: 230,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Channel: Open Source Templates',
        body: 'Give away 20+ strategy & architecture board templates on GitHub. Organic SEO compounding from template searches.',
        x: 60,
        y: -20,
        width: 230,
        color: 'slate',
        author: 'agent',
      },
      {
        title: 'Retention: Shared Multiplayer Boards',
        body: 'When a user shares a live board link with a teammate or agent, virality kicks in. Collaboration creates switching cost.',
        x: 60,
        y: 180,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
      {
        title: 'North Star Metric: Active Co-Sessions',
        body: 'Track weekly active boards where both human edits and agent tool calls occurred within the same 15-minute window.',
        x: 440,
        y: -20,
        width: 230,
        color: 'lavender',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 2, label: 'activates' },
      { sourceIndex: 0, targetIndex: 3, label: 'powers' },
      { sourceIndex: 1, targetIndex: 2, label: 'targets' },
      { sourceIndex: 1, targetIndex: 4, label: 'retains' },
      { sourceIndex: 2, targetIndex: 5, label: 'drives' },
      { sourceIndex: 3, targetIndex: 5, label: 'compounds' },
      { sourceIndex: 4, targetIndex: 5, label: 'measures' },
    ],
  },
  {
    id: 'swot-analysis',
    title: 'Agentic SWOT & Strategic Matrix',
    category: 'Analysis',
    badge: 'Essential',
    description: 'Exhaustive 4-quadrant strategic breakdown comparing internal capabilities with external market shifts.',
    suggestedPrompt: 'Analyze this SWOT board. For each weakness and threat, generate a concrete tactical countermeasure note and link them.',
    nodes: [
      {
        title: 'STRENGTHS: First-mover in WebMCP',
        body: '• Native document.modelContext support\n• Zero round-trip client tool execution\n• High tactile UX polish and delightful feel',
        x: -300,
        y: -200,
        width: 240,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'WEAKNESSES: Emerging Standard Awareness',
        body: '• WebMCP is nascent (requires Chrome flags or ChatGPT browser)\n• Need fallback simulator for standard Safari/Firefox users',
        x: 100,
        y: -200,
        width: 240,
        color: 'coral',
        author: 'human',
      },
      {
        title: 'OPPORTUNITIES: Browser Agent Ecosystem',
        body: '• OpenAI, Google Chrome & Cloudflare pushing WebMCP\n• Millions of ChatGPT users gain in-browser canvas superpowers',
        x: -300,
        y: 120,
        width: 240,
        color: 'mint',
        author: 'agent',
      },
      {
        title: 'THREATS: Legacy Whiteboard Add-ons',
        body: '• Incumbents bolting basic chat sidebars onto existing infinite canvases\n• Must win on agent ergonomics and tool density',
        x: 100,
        y: 120,
        width: 240,
        color: 'butter',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 2, label: 'capitalizes on' },
      { sourceIndex: 1, targetIndex: 3, label: 'vulnerable to' },
    ],
  },
  {
    id: 'user-journey',
    title: 'User Experience & Aha-Moment Map',
    category: 'Product',
    badge: 'Product',
    description: 'Map user emotion, friction points, agent intervention moments, and the path to initial delight.',
    suggestedPrompt: 'Identify the highest drop-off risk in this journey and add 2 automated agent assists to guide the user to their first win.',
    nodes: [
      {
        title: 'Phase 1: Discovery & Land',
        body: 'User opens Boardify via link or search. Sees pre-seeded interactive sticky notes and immediate live WebMCP status.',
        x: -450,
        y: 0,
        width: 220,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Phase 2: First Note Creation',
        body: 'Double clicks canvas or taps "New note". Types a rough idea or problem statement. Zero onboarding friction.',
        x: -180,
        y: 0,
        width: 220,
        color: 'slate',
        author: 'human',
      },
      {
        title: 'Phase 3: Agent Pulls Up a Chair',
        body: 'Agent in ChatGPT or Agent Studio reads canvas via get_canvas_state. Instantly spawns 4 structured branches with bezier wires.',
        x: 90,
        y: 0,
        width: 220,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Phase 4: The Aha! Moment',
        body: 'User watches the Agent Ghost cursor pan and tidy the board. User realizes: "I never have to stare at a blank whiteboard again."',
        x: 360,
        y: -100,
        width: 230,
        color: 'sage',
        author: 'agent',
      },
      {
        title: 'Phase 5: Export & Ship',
        body: 'User clicks export to Markdown/Mermaid and pastes directly into their engineering sprint ticket or strategy memo.',
        x: 640,
        y: 0,
        width: 220,
        color: 'lavender',
        author: 'human',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'next' },
      { sourceIndex: 1, targetIndex: 2, label: 'triggers' },
      { sourceIndex: 2, targetIndex: 3, label: 'produces' },
      { sourceIndex: 3, targetIndex: 4, label: 'converts to' },
    ],
  },
  {
    id: 'system-architecture',
    title: 'Distributed System & AI Agent Pipeline',
    category: 'Engineering',
    badge: 'Technical',
    description: 'Blueprint microservices, event streams, WebMCP client tool interfaces, and Firestore sync layers.',
    suggestedPrompt: 'Review this architecture for scalability bottlenecks and add a caching layer and rate limiter node with appropriate wires.',
    nodes: [
      {
        title: 'Browser Client (React/Next.js)',
        body: 'Runs Canvas Engine, pan/zoom camera, DOM nodes, SVG wire renderer, and WebMCP listener.',
        x: -400,
        y: -100,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'WebMCP Tool Layer (document.modelContext)',
        body: 'Exposes 12 deterministic JSON-schema tools. Zero network overhead — runs directly in client window context.',
        x: -100,
        y: -220,
        width: 240,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'AI Browser Agent (ChatGPT / Chrome AI)',
        body: 'Discovers tools automatically on page load. Invokes tool calls with structured JSON parameters.',
        x: -100,
        y: 40,
        width: 240,
        color: 'lavender',
        author: 'agent',
      },
      {
        title: 'Firebase Firestore Realtime DB',
        body: 'Multiplayer synchronizer. Broadcasts note coordinates, text diffs, and live agent cursor positions to all connected peers.',
        x: 230,
        y: -100,
        width: 240,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'Export Engine (JSON / Markdown / Mermaid)',
        body: 'Serializes graph state into reproducible artifacts for engineering PRs, wikis, and documentation.',
        x: 530,
        y: -100,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 2, targetIndex: 1, label: 'calls tools' },
      { sourceIndex: 1, targetIndex: 0, label: 'mutates state' },
      { sourceIndex: 0, targetIndex: 3, label: 'syncs live' },
      { sourceIndex: 3, targetIndex: 4, label: 'exports' },
    ],
  },
  {
    id: 'creative-storyboard',
    title: 'Narrative Arc & Storyboarding Flow',
    category: 'Creative',
    badge: 'Story',
    description: 'Orchestrate plot hooks, character arcs, escalating tension, midpoint reversals, and satisfying resolutions.',
    suggestedPrompt: 'Add a dramatic midpoint twist to this story arc and link it with two character development sub-plots.',
    nodes: [
      {
        title: 'Act 1: The Inciting Incident',
        body: 'Protagonist discovers an anomalous browser agent that refuses to stay in the sidebar chat box and begins drawing on the screen.',
        x: -360,
        y: 0,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Act 2A: Rising Friction',
        body: 'Human tries to organize a massive product roadmap alone. The agent watches, learns the team taxonomy, and starts anticipating links.',
        x: -90,
        y: -140,
        width: 230,
        color: 'slate',
        author: 'human',
      },
      {
        title: 'Act 2B: The Midpoint Shift',
        body: 'Deadline looms. Human hands the agent 3 words. In seconds, a 20-node strategic tapestry appears. Paradigm shifts from solitary to symbiosis.',
        x: 180,
        y: 0,
        width: 240,
        color: 'coral',
        author: 'agent',
      },
      {
        title: 'Act 3: The Climax & Resolution',
        body: 'The presentation wows the executive board. Whiteboards are permanently redefined as collaborative human-agent thinking environments.',
        x: 480,
        y: 0,
        width: 230,
        color: 'mint',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 1, label: 'escalates to' },
      { sourceIndex: 1, targetIndex: 2, label: 'forces' },
      { sourceIndex: 2, targetIndex: 3, label: 'culminates in' },
    ],
  },
  {
    id: 'ice-prioritization',
    title: 'Feature Prioritization Matrix (ICE Framework)',
    category: 'Product',
    badge: 'Framework',
    description: 'Score potential features by Impact (1-10), Confidence (1-10), and Ease (1-10) to determine sprint sequencing.',
    suggestedPrompt: 'Score all features on the board using the ICE formula (Impact × Confidence × Ease) and rearrange them into High, Medium, and Backlog columns.',
    nodes: [
      {
        title: 'Feature: Mermaid Diagram Export',
        body: 'Impact: 9 | Confidence: 9 | Ease: 8\nICE Score: 648\nStatus: High Priority — huge win for technical users.',
        x: -300,
        y: -140,
        width: 230,
        color: 'sage',
        author: 'human',
      },
      {
        title: 'Feature: Voice-to-Canvas Audio Notes',
        body: 'Impact: 8 | Confidence: 7 | Ease: 6\nICE Score: 336\nStatus: Medium Priority — explore Web Speech API integration.',
        x: -300,
        y: 100,
        width: 230,
        color: 'butter',
        author: 'human',
      },
      {
        title: 'Feature: Real-time Multi-Agent Swarms',
        body: 'Impact: 10 | Confidence: 6 | Ease: 4\nICE Score: 240\nStatus: Experimental — allows multiple named agents to debate on board.',
        x: 40,
        y: -140,
        width: 230,
        color: 'lavender',
        author: 'agent',
      },
      {
        title: 'Feature: Custom Note Shapes & Frames',
        body: 'Impact: 6 | Confidence: 8 | Ease: 7\nICE Score: 336\nStatus: Post-MVP polish.',
        x: 40,
        y: 100,
        width: 230,
        color: 'slate',
        author: 'agent',
      },
    ],
    edges: [
      { sourceIndex: 0, targetIndex: 2, label: 'enables' },
    ],
  },
];
